plugins {
    id "com.peterabeles.gversion" version "1.11.0"
    id "com.diffplug.spotless" version "8.10.3"
}

apply plugin: 'com.android.application'

//
// build.gradle in TeamCode
//
// Most of the definitions for building your module reside in a common, shared
// file 'build.common.gradle'. Being factored in this way makes it easier to
// integrate updates to the FTC into your code. If you really need to customize
// the build definitions, you can place those customizations in this file, but
// please think carefully as to whether such customizations are really necessary
// before doing so.

// Custom definitions may go here

// Include common definitions from above.
apply from: '../build.common.gradle'
apply from: '../build.dependencies.gradle'

android {
    namespace = 'org.firstinspires.ftc.teamcode'

    packagingOptions {
        jniLibs.useLegacyPackaging true
    }
}

repositories {
    maven {
        url 'https://repo.dairy.foundation/releases'
    }
}

dependencies {
    implementation project(':FtcRobotController')

    implementation 'dev.nextftc.v2:control:0.2.0'
    implementation 'dev.nextftc.v2:hardware:0.2.0'
    implementation 'dev.nextftc.v2:robot:0.2.0'
}

project.preBuild.dependsOn(createVersionFile)
project.preBuild.dependsOn(spotlessApply)
project.build.dependsOn(spotlessApply)

gversion {
    srcDir = "src/main/java/"
    classPackage = "org.firstinspires.ftc.teamcode.generated"
    className = "BuildConstants"
    dateFormat = "yyyy-MM-dd HH:mm:ss z"
    timeZone = "America/Chicago"
    indent = "  "
}

spotless {
    java {
        target fileTree('.') {
            include '**/*.java'
            exclude '**/build/**', '**/build-*/**', '**/bin/**', '**/deploy/**', '**/generated/**'
        }
        toggleOffOn()
        //        googleJavaFormat()
        princeOfSpace('2.2.0')
                .indentStyle('SPACES') // or 'TABS'
                .indentSize(2)
                .lineLength(120)
                .wrapStyle('WIDE') // or 'BALANCED', 'NARROW'
                .closingParenOnNewLine(true)
                .trailingCommas(true)
                .javaLanguageLevel(17)
        removeUnusedImports()
        shortenFullyQualifiedTypes()
        trimTrailingWhitespace()
        endWithNewline()
    }
    groovyGradle {
        target fileTree('.') {
            include '**/*.gradle'
            exclude '**/build/**', '**/build-*/**'
        }
        greclipse()
        leadingTabsToSpaces(4)
        trimTrailingWhitespace()
        endWithNewline()
    }
    format 'misc', {
        target fileTree('.') {
            include '**/*.md', '**/.gitignore'
            exclude '**/build/**', '**/build-*/**'
        }
        trimTrailingWhitespace()
        leadingTabsToSpaces(2)
        endWithNewline()
    }
}
